BaseUrl: "https://motomizuki.github.io"
LanguageCode: "jp"
Title: "Blog"

Params:
  Author: "motomizuki"
  GoogleAnalyticsUserID: "UA-55005303-5"
  Twitter: "motomizuki"
  Github: "motomizuki"
  ShowRelatedPost: false
  Disqus: "unresolved"
  SyntaxHighlightTheme: "github.min.css"

Indexes:
  tag: "tags"

permalinks:
  post: /blog/:year/:month/:day/:slug/

MetadataFormat: "yaml"
