baseurl = "https://motomizuki.github.io"


title = "Motomizuki Blog"
languageCode = "ja"
disqusShortname = "Moto Blo" # Optional, enable Disqus integration
MetaDataFormat = "toml"

[author]
    name = "motomizuki"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Your default page description"
    defaultKeywords = "your,default,page,keywords"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-09 layout-reverse"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    tagline = "Book,  Classic,  Programming"

    # Metadata used to drive integrations.
    googleAnalytics = "<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-29342124-2', 'auto');ga('send', 'pageview');</script>"

    # Sidebar social links, avoid enabling too many of these if possible.
    # These should be full URLs.
    github = "https://github.com/motomizuki"
    twitter = "https://twitter.com/motomizuki"
